version: "3"

# networks:
#   academe-platform_sociobee_network:
#     external: true
networks:
  my_network:
    driver: bridge

volumes:
  data-volume:


services:
  mysql:
    image: mysql
    build: ./Model
    volumes:
      #- ./Model/init.sql:/docker-entrypoint-initdb.d/dump.sql
      - data-volume:/var/lib/mysql
    container_name: mysql
    command: --default-authentication-plugin=caching_sha2_password 
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - my_network
  api:
    container_name: MVE
    platform: linux/x86_64
    build: .
    links:
      - mysql
    restart: always
    tty: true
    volumes:
      - ./:/recommendersystem
    ports:
      - 8001:8001
    env_file:
      - .env
    environment:
      - APP_SECRET_STRING=${APP_SECRET_STRING}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE=${DATABASE}
      - DATABASE_HOST=${DATABASE_HOST}
    depends_on:
      - mysql
    networks:
      - my_network



